# image
FROM python:3.9-slim

WORKDIR /app

# Ao invés de usar ADD . /app, resolvi apenas copiar o arquivo
COPY requirements.txt . 

# Em seguida, mando instalar as dependências do arquivo

RUN pip install --no-cache-dir -r requirements.txt   

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]
